# Generated by Django 5.2.5 on 2025-08-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У')], max_length=10)),
                ('color', models.CharField(choices=[('red', 'Красный'), ('black', 'Черный'), ('blue', 'Синий'), ('green', 'Зеленый'), ('yellow', 'Желтый')], max_length=10)),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Внедорожник'), ('hatchback', 'Хэтчбек'), ('coupe', 'Купе'), ('minivan', 'Минивэн')], max_length=15)),
                ('price_range', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
