# Generated by Django 5.2.5 on 2025-08-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL изображения автомобиля', null=True, verbose_name='Ссылка на фото'),
        ),
    ]
