# Generated by Django 5.2.5 on 2025-08-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_car_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price_range',
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фото'),
        ),
    ]
