# Generated by Django 5.2.5 on 2025-09-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_car_price_range_car_price_alter_car_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image_url',
        ),
        migrations.AddField(
            model_name='car',
            name='image_url1',
            field=models.URLField(blank=True, null=True, verbose_name='Фото 1'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url2',
            field=models.URLField(blank=True, null=True, verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url3',
            field=models.URLField(blank=True, null=True, verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url4',
            field=models.URLField(blank=True, null=True, verbose_name='Фото 4'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url5',
            field=models.URLField(blank=True, null=True, verbose_name='Фото 5'),
        ),
        migrations.AddField(
            model_name='car',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео'),
        ),
    ]
